-- MySQL Script generated by MySQL Workbench
-- Tue Jul 23 13:27:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`language` (
  `name` VARCHAR(45) NOT NULL,
  `la_region_id` INT NULL,
  `language_id` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `us_region_id` INT NULL,
  PRIMARY KEY (`language_id`));


-- -----------------------------------------------------
-- Table `mydb`.`la_region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`la_region` (
  `name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NULL,
  `language_id` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `education_level` VARCHAR(45) NULL,
  `highway_access` VARCHAR(45) NULL,
  `average_income` VARCHAR(45) NULL,
  `average_age` INT NULL,
  `la_region_id` INT NOT NULL,
  PRIMARY KEY (`la_region_id`),
  CONSTRAINT `language_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`language` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`us_region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`us_region` (
  `name` VARCHAR(45) NOT NULL,
  `language_id` INT NULL,
  `county_id` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `farm_crop` VARCHAR(45) NULL,
  `us_region_id` INT NOT NULL,
  `coastal` TINYINT NULL,
  PRIMARY KEY (`us_region_id`),
  CONSTRAINT `language_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`language` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`master_region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`master_region` (
  `master_region_id` INT NOT NULL,
  `name_of_region` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `coast` TINYINT NULL,
  `region_id` INT NULL,
  PRIMARY KEY (`master_region_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`region` (
  `region_id` INT NOT NULL,
  `master_region_id` INT NULL,
  `name` VARCHAR(45) NULL,
  `population_estimated` INT NULL,
  `us_census` INT NULL,
  PRIMARY KEY (`region_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sub_region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sub_region` (
  `sub_region_id` INT NOT NULL,
  `master_region_id` INT NULL,
  `name` VARCHAR(45) NULL,
  `population_estimated` INT NULL,
  `us_census` INT NULL,
  PRIMARY KEY (`sub_region_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`crop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`crop` (
  `crop_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`crop_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`region_crop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`region_crop` (
  `id` INT NOT NULL,
  `region_id` INT NULL,
  `crop_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`region_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`region_language` (
  `id` INT NOT NULL,
  `region_id` INT NULL,
  `language_id` INT NULL,
  `region_languagecol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;
